<a href="https://colab.research.google.com/github/1ashish1105/PyTorch/blob/main/Tensors_in_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch
print(torch.__version__)

2.11.0+cu128


In [6]:
if torch.cuda.is_available():
  print("GPU is available.")
  print(f"Using GPU:{torch.cuda.get_device_name(0)}")

GPU is available.
Using GPU:Tesla T4


**Creating a tensor**

In [7]:
a=torch.empty(2,3)

In [8]:
type(a)

torch.Tensor

Tensor with all value 0

In [9]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

Tensor with all value 1

In [10]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

Tensor with Random Value

In [11]:
torch.rand(2,3)

tensor([[0.1801, 0.1391, 0.3137],
        [0.2606, 0.3649, 0.4045]])

Use of seed

In [12]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

Sending my own value

In [13]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
print("using arange ->", torch.arange(0,10,2))
print("using linspace ->", torch.linspace(0,10,5))
# Eye print identity matrix and we give its value of size.
print("eye->",torch.eye(5));
# Full helps us to we give shape and give what element we want
print("full->",torch.full((2,3),5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
eye-> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
full-> tensor([[5, 5, 5],
        [5, 5, 5]])


Tensor Shape

In [18]:
x=torch.tensor([[1,2,3],[4,5,6]])

In [19]:
x.shape

torch.Size([2, 3])

In [21]:
torch.empty_like(x)

# It creates a tensor whose shape is similar like x

tensor([[    138560990846352,          1104059024,                   0],
        [                  0,                   0, 7310593858020254331]])

In [23]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [24]:
x.dtype

torch.int64

In [25]:
torch.tensor([1,2,3],dtype=int)

tensor([1, 2, 3])

In [26]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [27]:
x+2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [28]:
x*2

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [30]:
((x*100)//3)%2

tensor([[1, 0, 0],
        [1, 0, 0]])

You can also do element wise operations with two vectos

In [35]:
torch.argmax(x)

tensor(5)

In [42]:
y=torch.tensor([1.,2.,3.])

In [45]:
torch.max(y)

tensor(3.)

In [47]:
print(torch.std(y))
print(torch.var(y))

tensor(1.)
tensor(1.)


We can also perform Matrix calculations of two vectors also.

In [49]:
v1=torch.tensor([1,2,3])
v2=torch.tensor([4,5,6])

In [50]:
v1+v2

tensor([5, 7, 9])

In [52]:
v1*v2

tensor([ 4, 10, 18])

In [53]:
f=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
g=torch.tensor([[9,8,7],[6,5,4],[3,2,1]])

In [55]:
torch.matmul(f,g)

tensor([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]])

**Perfoeming Operations on GPU**

In [57]:
torch.cuda.is_available()

True

In [58]:
import torch
import time

In [61]:
device=torch.device('cuda')

In [62]:
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [63]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [66]:
x.to(device)

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')

In [69]:
print(x.flatten())

tensor([1, 2, 3, 4, 5, 6])
